Repository Git-For-Geeks/Webdev-mini-projects, pull requests merged in 2022-10, with the labels that each got.

#17 Added Random Quote Generator
  Random Quote Generator/index.html
  Random Quote Generator/script/script.js
  Random Quote Generator/style/style.css
Labels: hard, git-for-geeks

#18 Create: Tourism Website
  Tourism_Website/booking.html
  Tourism_Website/css/booking.css
  Tourism_Website/css/style.css
  Tourism_Website/images/client-logo-1.png
  Tourism_Website/images/client-logo-2.png
  Tourism_Website/images/client-logo-3.png
  Tourism_Website/images/client-logo-4.png
  Tourism_Website/images/footer-bg.jpg
  Tourism_Website/images/home-bg-1.jpg
  Tourism_Website/images/home-bg-2.jpg
  Tourism_Website/images/home-bg-3.jpg
  Tourism_Website/images/product-1.jpg
  Tourism_Website/images/product-2.jpg
  Tourism_Website/images/product-3.JPG
  Tourism_Website/images/product-4.JPG
  Tourism_Website/images/product-5.jpg
  Tourism_Website/images/product-6.jpg
  Tourism_Website/images/serv-1.png
  Tourism_Website/images/serv-2.png
  Tourism_Website/images/serv-3.png
  Tourism_Website/images/serv-4.png
  Tourism_Website/images/serv-5.png
  Tourism_Website/images/serv-6.png
  Tourism_Website/index.html
  Tourism_Website/js/script.js
Labels: easy, git-for-geeks

#20 This is an ADVERSTISEMENT PLOT
  Ad Plot/images/icon-clock.svg
  Ad Plot/images/icon-ethereum.svg
  Ad Plot/images/icon-view.svg
  Ad Plot/images/image-avatar.png
  Ad Plot/images/image-equilibrium.jpg
  Ad Plot/index.html
  Ad Plot/style.css
Labels: medium, git-for-geeks, hacktoberfest-accepted

#21 Changed the default theme to dark
  Battery Indicator/index.html
Labels: medium, git-for-geeks, hacktoberfest-accepted

#22 On hover theme change
  Battery Indicator/script.js
  Battery Indicator/style.css
Labels: medium, git-for-geeks, hacktoberfest-accepted

#23 password checker
  Password checker/index.html
  Password checker/script.js
  Password checker/style.css
Labels: medium, git-for-geeks, hacktoberfest-accepted, hacktober

#25 Cookie consent Banner
  Cookie consent Banner/index.html
  Cookie consent Banner/main.js
  Cookie consent Banner/style.css
Labels: medium, git-for-geeks, hacktoberfest-accepted

#28 added links to images
  IJNLC Clone/Indexing.html
Labels: easy, git-for-geeks, hacktober
